#!/usr/bin/env ruby
Hecks::DomainBuilder.build "soccer_season" do |hexagon|
  hexagon.module 'Pitches' do |pitches|
    pitches.head("Pitch").attributes('name:value')
  end

  hexagon.module 'Teams' do |teams|
    teams.head("Team").attributes('name:value')
  end

  hexagon.module 'Players' do |players|
    players.head("Player").attributes('name:value', 'team:teams::team')
    players.reference("teams::team")
  end

  hexagon.module 'Matches' do |matches|
    matches.head("Match").attributes(
      "fixture:fixture",
      "result:result",
      "pitch:pitches::pitch",
      "goals:[goal]",
      "teams:teams::[team]"
    )
    matches.value("Result").attributes("winner:teams::team", "type:value")
    matches.value("Goal").attributes("time:value", "player:players::player")
    matches.value("Fixture").attributes("season:value", "date:value", "time:value")
    matches.reference("pitches::pitch")
    matches.reference("teams::team")
  end
end
