#!/usr/bin/env ruby
Hecks::DomainBuilder.build "pizza_builder" do |pizza_builder|
  pizza_builder.module 'Pizzas' do |pizzas|
    pizzas.head("Pizza").attributes('name:string', 'description:string', 'toppings:[topping]', 'chef:chef')
    pizzas.value("Topping").attributes('name:string')
    pizzas.value("Chef").attributes('name:string')
  end

  pizza_builder.module 'Orders' do |orders|
    orders.head("Order").attributes('line_items:[line_item]')
    orders.value("LineItem").attributes('pizza_name:string', 'quantity:integer', 'price:currency', "pizza:pizzas::pizza")
    orders.reference("pizzas::pizza")
  end
end
